homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 940
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend: !include frontend.yaml

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

recorder:
#  purge_interval: 1
#  purge_keep_days: 7
  db_url: !secret recorder_db_url

# View all events in a logbook
logbook:

logger:
  default: info
# Track the sun
sun:

# Text to speech
tts:
  - platform: google

map:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret panel_iframe_url
  terminal:
    title: Terminal
    icon: mdi:console-line
    url: !secret panel_iframe_url_terminal
#  ide:
#    title: IDE
#    icon: mdi:code-braces
#    url: !secret panel_iframe_url_ide
#  nodered:
#    title: Node-RED
#    icon: mdi:sitemap
#    url: !secret panel_iframe_url_node_red
   
wake_on_lan:
#customizer:
#  custom_ui: local

automation: !include_dir_list automation
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
cover: !include cover.yaml
#customizer: !include customizer.yaml
device_tracker: !include device_tracker.yaml
google: !include google.yaml
google_assistant: !include google_assistant.yaml
group: !include groups.yaml
history_graph: !include history_graph.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
light: !include light.yaml
media_player: !include media_player.yaml
mqtt: !include mqtt.yaml
nest: !include nest.yaml
notify: !include notify.yaml
proximity: !include proximity.yaml
#scene: !include_dir_list scenes
script: !include_dir_merge_named scripts
sensor: !include sensor.yaml
switch: !include switch.yaml
weather: !include weather.yaml
zone: !include_dir_list zone
zwave: !include zwave.yaml